# Generated by Django 2.2 on 2019-04-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biljnevrsteapp', '0002_biljnevrste_sinonim'),
    ]

    operations = [
        migrations.AddField(
            model_name='biljnevrste',
            name='opis',
            field=models.CharField(default='opis', max_length=100),
        ),
    ]
