# Generated by Django 2.2.1 on 2019-05-08 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biljnevrsteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biljna_vrsta',
            fields=[
                ('ID_biljne_vrste', models.AutoField(primary_key=True, serialize=False)),
                ('hrvatski_naziv_vrste', models.CharField(max_length=100)),
                ('latinski_naziv', models.CharField(max_length=100)),
                ('sinonim_vrste', models.CharField(max_length=100)),
                ('opis_vrste', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Podvrsta',
            fields=[
                ('ID_podvrste', models.AutoField(primary_key=True, serialize=False)),
                ('naziv_podvrste', models.CharField(max_length=100)),
                ('ID_biljne_vrste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biljnevrsteapp.Biljna_vrsta')),
            ],
        ),
        migrations.CreateModel(
            name='Porodica',
            fields=[
                ('ID_porodice', models.AutoField(primary_key=True, serialize=False)),
                ('hrvatski_naziv_porodice', models.CharField(max_length=100)),
                ('latinski_naziv_porodice', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rod',
            fields=[
                ('ID_roda', models.AutoField(primary_key=True, serialize=False)),
                ('naziv_roda', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sistematicar',
            fields=[
                ('ID_sistematicara', models.AutoField(primary_key=True, serialize=False)),
                ('naziv_sistematicara', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Slika',
            fields=[
                ('ID_slike', models.AutoField(primary_key=True, serialize=False)),
                ('naziv_slike', models.CharField(max_length=50)),
                ('opis_slike', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Uporabni_dio',
            fields=[
                ('ID_uporabni_dio', models.AutoField(primary_key=True, serialize=False)),
                ('uporabni_dio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Uporabni_dio_vrste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_biljna_vrsta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biljnevrsteapp.Biljna_vrsta')),
                ('ID_uporabni_dio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biljnevrsteapp.Uporabni_dio')),
            ],
        ),
        migrations.CreateModel(
            name='Varijet',
            fields=[
                ('ID_varijeta', models.AutoField(primary_key=True, serialize=False)),
                ('naziv_varijeta', models.CharField(max_length=100)),
                ('ID_podvrste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biljnevrsteapp.Podvrsta')),
            ],
        ),
        migrations.DeleteModel(
            name='BiljneVrste',
        ),
        migrations.AddField(
            model_name='slika',
            name='ID_uporabni_dio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biljnevrsteapp.Uporabni_dio'),
        ),
        migrations.AddField(
            model_name='porodica',
            name='ID_roda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biljnevrsteapp.Rod'),
        ),
        migrations.AddField(
            model_name='biljna_vrsta',
            name='ID_roda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biljnevrsteapp.Rod'),
        ),
    ]
