# Generated by Django 2.2 on 2019-05-01 19:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('biljnevrsteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biljnavrsta',
            options={'verbose_name': 'Biljna vrsta', 'verbose_name_plural': 'Biljne vrste'},
        ),
        migrations.AlterModelOptions(
            name='podvrsta',
            options={'verbose_name': 'Podvrsta', 'verbose_name_plural': 'Podvrste'},
        ),
        migrations.AlterModelOptions(
            name='porodica',
            options={'verbose_name': 'Porodica', 'verbose_name_plural': 'Porodice'},
        ),
        migrations.AlterModelOptions(
            name='rod',
            options={'verbose_name': 'Rod', 'verbose_name_plural': 'Rodovi'},
        ),
        migrations.AlterModelOptions(
            name='sistematicar',
            options={'verbose_name': 'Sistematicar', 'verbose_name_plural': 'Sistematicari'},
        ),
        migrations.AlterModelOptions(
            name='slika',
            options={'verbose_name': 'Slika', 'verbose_name_plural': 'Slike'},
        ),
        migrations.AlterModelOptions(
            name='uporabnidio',
            options={'verbose_name': 'Uporabni dio', 'verbose_name_plural': 'Uporabni dijelovi'},
        ),
        migrations.AlterModelOptions(
            name='varijet',
            options={'verbose_name': 'Varijet', 'verbose_name_plural': 'Varijeti'},
        ),
    ]
