# Generated by Django 2.2 on 2019-06-11 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biljnevrsteapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porodica',
            name='ID_roda',
        ),
        migrations.RemoveField(
            model_name='uporabnidio',
            name='biljna_vrsta',
        ),
        migrations.AddField(
            model_name='biljnavrsta',
            name='uporabni_dio',
            field=models.ManyToManyField(to='biljnevrsteapp.UporabniDio'),
        ),
        migrations.AddField(
            model_name='rod',
            name='ID_porodice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biljnevrsteapp.Porodica'),
        ),
        migrations.AlterField(
            model_name='biljnavrsta',
            name='opis_vrste',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='slika',
            name='naziv_slike',
            field=models.ImageField(upload_to=''),
        ),
    ]
