# Generated by Django 2.2 on 2019-06-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biljnevrsteapp', '0002_auto_20190611_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slika',
            name='opis_slike',
            field=models.CharField(max_length=1000),
        ),
    ]
