# Generated by Django 2.2 on 2019-06-10 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biljnevrsteapp', '0002_auto_20190521_2010'),
        ('biljnevrsteapp', '0002_auto_20190514_1753'),
    ]

    operations = [
    ]
